import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useRef, useState } from 'react';
import '../luma.css';
export const Route=createFileRoute('/')({head:()=>({meta:[{title:'Luma — Dentistry in a different light'},{name:'description',content:'Thoughtfully designed dental care. Explore cosmetic, restorative and preventive dentistry with Luma Dental Studio.'}]}),component:Luma});
const services=[{id:'01',name:'Smile aesthetics',tag:'A little more you.',image:'/images/luma-smile.svg',alt:'Editorial portrait with a natural smile',description:'Whitening, bonding and veneers. Explore the possibilities with a plan that respects your natural features.'},{id:'02',name:'Restorative dentistry',tag:'Precision. With purpose.',image:'/images/luma-hero.svg',alt:'Concept rendering of a porcelain crown and titanium implant',description:'Crowns, restorations and implant options. A clinical assessment helps determine the right path for your oral health.'},{id:'03',name:'Everyday care',tag:'Good habits. Lasting care.',image:'/images/luma-clinic.svg',alt:'Concept interior of a contemporary dental treatment room',description:'Examinations, cleaning and preventive care. The everyday foundations of a healthier smile.'}];
function Arrow({diagonal=false}:{diagonal?:boolean}){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal?'M6 18 18 6M6 6h12v12':'M4 12h16m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.5"/></svg>}
function Spark(){return <svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M20 1v38M1 20h38M7 7l26 26M7 33 33 7" stroke="currentColor" strokeWidth="1.2"/></svg>}
function Luma(){const [menu,setMenu]=useState(false),[modal,setModal]=useState(false),[sent,setSent]=useState(false),[active,setActive]=useState<string|null>(null);const dialog=useRef<HTMLDialogElement>(null),hero=useRef<HTMLElement>(null);
useEffect(()=>{if(modal){setSent(false);dialog.current?.showModal();}else dialog.current?.close();},[modal]);
useEffect(()=>{const items=document.querySelectorAll('.reveal');const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target);}}),{threshold:.08});items.forEach(el=>{el.classList.add('observed');obs.observe(el);});return()=>obs.disconnect();},[]);
const book=()=>setModal(true);
return <div className="luma-site"><a className="skip" href="#main">Skip to content</a><div className="page-shell">
<header className="nav"><a className="brand" href="#" aria-label="Luma Dental Studio home"><span className="brand-icon"><Spark/></span>luma<span className="registered">®</span></a><nav className={menu?'nav-links open':'nav-links'} aria-label="Main navigation">{[['Our approach','approach'],['Our care','care'],['The experience','experience'],['Questions','questions']].map(([text,id])=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{text}</a>)}</nav><button className="nav-book" onClick={book}>Let’s talk <Arrow diagonal/></button><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button></header>
<main id="main"><section className="hero" ref={hero} onPointerMove={e=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();hero.current?.style.setProperty('--mx',`${((e.clientX-r.left)/r.width-.5)*12}px`);hero.current?.style.setProperty('--my',`${((e.clientY-r.top)/r.height-.5)*8}px`);}} onPointerLeave={()=>{hero.current?.style.setProperty('--mx','0px');hero.current?.style.setProperty('--my','0px');}}>
<div className="hero-visual"><img className="hero-image" src="/images/luma-hero.svg" alt="Sculptural porcelain tooth floating above precision titanium components" fetchPriority="high"/><div className="hero-light"/></div>
<div className="hero-copy"><p className="pill"><span/> DENTISTRY, IN A DIFFERENT LIGHT</p><h1>A better smile.<br/>A different<br/><em>feeling.</em></h1><p className="hero-intro">Considered care. Beautifully natural results.<br/>A dental experience shaped around you.</p><button className="button primary" onClick={book}>Discover your possibilities <Arrow/></button><div className="hero-caption"><span className="fine-line"/><p>SCIENCE IN THE DETAILS.<br/>CONFIDENCE IN THE EVERYDAY.</p></div></div>
<div className="hero-top-note">DESIGNED WITH CARE<br/><span>LUMA DENTAL STUDIO</span></div><div className="annotation annotation-top"><span className="annotation-dot"/><span>A naturally brighter outlook</span></div><div className="annotation annotation-bottom"><span className="annotation-dot"/><span>Precision at every level</span></div><a className="hero-scroll" href="#approach"><span>EXPLORE LUMA</span><span className="scroll-circle">↓</span></a><span className="hero-index">01 — A NEW PERSPECTIVE</span>
</section>
<section className="principles" aria-label="Our care principles">{[['01','Prevention','Care for the long term.'],['02','Precision','Considered in every detail.'],['03','Comfort','Space to feel at ease.'],['04','Confidence','A smile that feels like you.']].map(([n,h,p])=><div key={n}><span>{n}</span><div><h2>{h}</h2><p>{p}</p></div></div>)}</section>
<section id="approach" className="intro section reveal"><p className="eyebrow"><span>✳</span> THE LUMA APPROACH</p><div><h2>Good dentistry goes<br/>beyond <em>your smile.</em></h2><div className="intro-bottom"><p>It’s how you’re welcomed. How clearly your options are explained. How much room you have to ask questions. We bring care and craft together, so every next step feels right.</p><a className="text-link" href="#experience">Meet a different kind of care <Arrow diagonal/></a></div></div></section>
<section id="care" className="care section"><div className="care-heading reveal"><div><p className="eyebrow">01 / OUR CARE</p><h2>Expertise for your smile.<br/><span>Attention for <em>you.</em></span></h2></div><p>Every smile has its own story.<br/>Your care should, too.</p></div><div className="service-grid">{services.map(s=><article className={`service-card reveal service-${s.id}`} key={s.id}><div className="service-photo"><img src={s.image} alt={s.alt} loading="lazy"/><span className="photo-tag">{s.id} / LUMA CARE</span></div><div className="service-body"><h3>{s.name}</h3><p>{s.tag}</p><button aria-expanded={active===s.id} onClick={()=>setActive(active===s.id?null:s.id)}><span>Explore the possibilities</span><span className="round-arrow">{active===s.id?'−':<Arrow diagonal/>}</span></button>{active===s.id&&<div className="service-detail"><p>{s.description}</p><button onClick={book}>Talk through your options <Arrow/></button></div>}</div></article>)}</div><div className="care-footer"><span>INDIVIDUAL PLANS. THOUGHTFUL CHOICES.</span><button onClick={book}>Not sure where to start? Let’s talk <Arrow/></button></div></section>
<section id="experience" className="experience section"><div className="experience-image reveal"><img src="/images/luma-clinic.svg" alt="Architectural concept of a bright, calm dental studio" loading="lazy"/><div className="image-caption"><span>ROOM TO BREATHE.</span><span>SPACE TO FEEL AT EASE. ↗</span></div></div><div className="experience-copy reveal"><p className="eyebrow">02 / THE EXPERIENCE</p><h2>Less uncertainty.<br/><em>More ease.</em></h2><p className="body-copy">Clear conversations make better care possible. We start by understanding what matters to you, then make a plan together.</p><div className="steps">{[['01','We listen.','Your concerns, your goals, your questions.'],['02','We explain.','A clear picture of your options and next steps.'],['03','We plan together.','Thoughtful choices, at a pace that feels right.']].map(([n,h,p])=><div key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div><Arrow diagonal/></div>)}</div><button className="button primary" onClick={book}>Start your conversation <Arrow/></button></div></section>
<section className="statement section reveal"><div className="statement-symbol"><Spark/></div><p>Not a different you.<br/><span>A more confident <em>you.</em></span></p><span className="eyebrow">THAT’S THE LUMA WAY.</span></section>
<section id="questions" className="faq section reveal"><div><p className="eyebrow">03 / A LITTLE CLARITY</p><h2>Before you<br/><em>take a seat.</em></h2><p className="body-copy">A few answers to help you<br/>feel more at home.</p></div><div className="faq-list">{[['What should I expect at my first visit?','We begin with your concerns and goals. Your clinician will explain the recommended examination, discuss the findings and outline the next steps with you.'],['How do I know which treatment is right for me?','A clinical assessment is the first step. We explain appropriate options, their expected outcomes and their limitations before you decide.'],['Can we discuss costs before treatment?','Yes. Request a written treatment plan and estimate before proceeding. Costs depend on your individual needs and the treatment you choose.'],['What if I feel anxious about dental care?','Tell the team before your visit. We can discuss what worries you, explain the process and agree on pauses to help you feel more in control.']].map(([q,a],i)=><details key={q}><summary><span className="faq-number">0{i+1}</span><span>{q}</span><span className="faq-plus">+</span></summary><p>{a}</p></details>)}</div></section>
<section className="closing reveal"><div><p className="eyebrow">A NEW CHAPTER, A NEW CONFIDENCE.</p><h2>Your smile.<br/><em>In a new light.</em></h2><button className="button primary" onClick={book}>Let’s start with you <Arrow/></button></div><div className="closing-art" aria-hidden="true"><Spark/><span>luma</span></div></section></main>
<footer><div className="footer-top"><a className="brand" href="#"><span className="brand-icon"><Spark/></span>luma<span className="registered">®</span></a><p>Considered care.<br/>Everyday confidence.</p><div><a href="#approach">Our approach</a><a href="#care">Our care</a><button onClick={book}>Get in touch <Arrow diagonal/></button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Luma Dental Studio</span><span>Concept website · Illustrative imagery</span><a href="#">BACK TO TOP ↑</a></div></footer>
<dialog ref={dialog} className="booking" onCancel={()=>setModal(false)} onClick={e=>{if(e.target===e.currentTarget)setModal(false);}}><button className="close-dialog" onClick={()=>setModal(false)} aria-label="Close consultation form">✕</button>{sent?<div className="success"><p className="eyebrow">YOUR NEXT STEP</p><h2>Let’s find<br/><em>your confidence.</em></h2><p>This is a concept preview. No request was sent or stored. A live appointment service will be connected before launch.</p><button className="button primary" onClick={()=>setModal(false)}>Back to Luma <Arrow/></button></div>:<><p className="eyebrow">LET’S START WITH YOU</p><h2>A brighter<br/><em>conversation.</em></h2><p>This consultation form is a preview. It does not send or store personal information.</p><form onSubmit={e=>{e.preventDefault();setSent(true);}}><label>Your name<input name="name" autoComplete="name" placeholder="Full name" required maxLength={100}/></label><label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/></label><label>What would you like to explore?<select name="treatment"><option>General consultation</option>{services.map(s=><option key={s.id}>{s.name}</option>)}</select></label><button className="button primary" type="submit">Preview your request <Arrow/></button><small>Demo only — no appointment is booked.</small></form></>}</dialog>
</div></div>}
